- Rakefile
- ext/Rakefile
- lib/sassc/functions_handler.rb
- lib/sassc/native.rb
- lib/sassc/native/native_functions_api.rb
- lib/sassc/native/sass_value.rb
- lib/sassc/script.rb
- lib/sassc/script/string.rb
- lib/tasks/libsass.rb
- sassc.gemspec
- test/functions_test.rb
Adds support for:
* Optional parameters in custom Sass functions
* Better exception handling for custom Sass functions
Bonus:
* Refactored Rakefile-related stuff for packaging/testing
@nickjs @bolandrm for review
> Allow optional params

- lib/sassc/error.rb
- lib/sassc/functions_handler.rb
- lib/sassc/native/native_functions_api.rb
- lib/sassc/script.rb
- lib/sassc/script/color.rb
- sassc.gemspec
- test/functions_test.rb
Adds support for `:sass_color`
Also brings in Sass dependency to ride `Script::Color` off of 
(*sad but probably the best way trombone*)
For review: @bolandrm @nickjs
> Support Sass color custom function arguments

- lib/sassc/functions_handler.rb
- lib/sassc/native/native_functions_api.rb
- lib/sassc/script.rb
- lib/sassc/script/string.rb
- test/functions_test.rb
Also refactors existing string-quoting stuff to use native quoted strings
For review @bolandrm
> Adds support for native quoted strings

- lib/sassc/functions_handler.rb
- lib/sassc/native/native_functions_api.rb
- test/functions_test.rb
> Adds Native.make_error(message) and refactors functions handler

- lib/sassc/native/native_functions_api.rb
- lib/sassc/script/color.rb
- test/functions_test.rb
> Add support for returning Sass Color types

- lib/sassc/engine.rb
- test/engine_test.rb
We are moving from the sass gem to sassc-ruby gem and found precision setting was missing from the API binding.
Our use case needs this to keep the output consistent.
> Exposed percision settings

- README.md
- lib/sassc/import_handler.rb
- lib/sassc/native/native_functions_api.rb
- test/custom_importer_test.rb
- test/functions_test.rb
- test/native_test.rb
Don't plan to merge until the official 3.3.0 release.
> update to libsass beta version

- README.md
- lib/sassc/version.rb
- lib/tasks/libsass.rb
- test/custom_importer_test.rb
- test/engine_test.rb
- test/functions_test.rb
- test/native_test.rb
Hello, I wanted to bump libsass to 3.3.2. I thought it might have a fix for an issue we're having (https://github.com/sass/libsass/issues/1097#issuecomment-164043059) but it didn't after all. Oh well. Thank you!!
> update to libsass 3.3.2

- lib/sassc/import_handler.rb
- lib/sassc/native/native_functions_api.rb
Pass an absolute `parent_path` to `Importer::imports(path, parent_path)` to address #27
> Pass absolute parent_path to importer

- README.md
Just a small change to the README, where a common English idiom was off by one letter.
> Switch easy to ease in order to use english idiom

- lib/sassc/engine.rb
- test/engine_test.rb
sassc raises an error when an empty template is passed (see https://github.com/sass/libsass/blob/b2a3d98ed384d2d19aa79157d08fa21c3e8043e0/src/sass_context.cpp#L390). rubysass accepts that however, that means the sass and sassc gems behave differently when passed the same input:
```ruby
Sass::Engine.new('', style: :compressed).render # => ""
SassC::Engine.new('', style: :compressed).render # raises SassC::SyntaxError
SassC::Engine.new(' ', style: :compressed).render # => ""
```
This change just short-circuits the whole `Engine#render`-method if the template is empty. This is the easiest solution I could see, but maybe I'm missing something.
A side note: While putting this together I noticed that the `:quiet`-option seems badly named, as it is more like a dry run if I understand it …
> Don't raise error when template is empty

- test/engine_test.rb
Continued from #31, these tests make it clear why `return @template.dup` is used instead of `return ''`.
> Add more tests for empty templates

- lib/tasks/libsass.rb
Like as redis/hiredis-rb@a5d7248dc886af7fa06b3a51c36071261b156963 commit, I'd like to be supported gmake on *BSD platform.
This patch includes standard ENV['MAKE'] variable to override manually and mswin nmake support (latter is untested).
> Support ${MAKE} env variables and default value for mswin/bsd/solaris.

- README.md
I think the README should include details on how to install the gem (i.e. it’s `gem 'sassc'`, not `gem 'sassc-ruby'`), and at least a basic example of how to use the `SassC` engine.
Some documentation on the options hash also be nice.
> Add more details on installation and usage

- lib/sassc/error.rb
- test/error_test.rb
When SyntaxError is raised, I want to see the broken sass file on error page. This is implemented in `Sass::SyntaxError` too.
Since we can know filename and lineno only from message, I implemented it by parsing it.
> Show sass file on the top of backtrace

- lib/sassc/engine.rb
- test/engine_test.rb
Adds a getter similar to `dependencies` for the source map string. 
I'm working on fixing a bug in `rails/sprockets` to do with its sassc source map support. Currently it's stripping out and decoding the inline source maps, this change will make the fix much simpler.
> Add source_map getter

- lib/sassc/engine.rb
- test/engine_test.rb
Adds support for the `omit_source_map_url` option w/ test. 
Useful when sassc engine is part of a pipeline and the generated map isn't final. e.g. sassc => autoprefixer.
> Add omit_source_map_url option

- lib/sassc/native/native_functions_api.rb
- lib/sassc/script/value_conversion.rb
- lib/sassc/script/value_conversion/list.rb
- test/functions_test.rb
Hello.
I was a bit surprised that all Sass value types were supported except `List`. I would find `List` useful in my own project, would you like to have it in, too?
Thank you!
> Add support for lists in functions.

- test/native_test.rb
@bolandrm sorry to bother, a patch has already been released to libsass. Would you mind also bumping this library?
Thanks!
> bump libsass to version 3.4.1

- README.md
- sassc.gemspec
- test/native_test.rb
Hi @bolandrm a few crashes have been corrected in libsass since it was last updated in this gem, would you mind taking a look over this PR?
Thanks!
> bump libsass to v3.4.3

- lib/sassc/script.rb
Hi there!
I was developing a rails application using the `sassc-rails` gem and I got an error like this:
`NameError: uninitialized constant Sass::Deprecation`
Then I realized that this gem was including the latest version of `sass` and it is requiring the modules individually in the `lib/sassc/script.rb` file.
I am not sure if this fix belongs here or the `require` is missing in some `sass` file.
Thoughts?
> Require Sass::Deprecation module

- sassc.gemspec
bundler is moved as dependency by 6458ff12.
However it seems bundler is used for only development for now.
> bundler is a development dependency

- test/engine_test.rb
- test/native_test.rb
This is an alternative to #80 to fix #79. I tried upgrading to the latest commit in 3.5-stable, but I couldn't compile the thing locally. It might be an issue with my enviroment though.
> Downgrade to libsass 3.5.2 to fix css imports

- sassc.gemspec
Hi @bolandrm , we have a gem that depends on SassC, one of our end-users was unable to install it. The fix was `gem install rake`. This crops up in the default `ruby` package in the Ubuntu repos, which supplies a `rake` executable in `/usr/bin/` but does not include the gem.
This change makes sense to me since libsass is compiled in a Rake task.
> Change rake to a runtime dependency from a development dependency

- .travis.yml
- sassc.gemspec
We won't provide precompiled versions for these Rubies, but we could still support them quite easily (minimal level of support, CI must pass but no manual testing).
Fixes #106
> Support ancient obsolete Rubies (v2.0.0+)

- lib/sassc/native.rb
- lib/sassc/native/native_functions_api.rb
Problem
===
sassc-ruby displays warnings on load the gem if `-w` options is passed to ruby interpreter.
```console
$ ruby -w -rsassc -e ''
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:
warning: method redefined; discarding old version
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:
warning: method redefined; discarding old version
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:
warning: method redefined; discarding old _make_data_context
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:
warning: method redefined; discarding old _make_data_context
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/ffi- …
```
> Reduce Ruby warnings

- .gitignore
- Rakefile
- ext/depend
- ext/extconf.rb
- lib/sassc/native.rb
- sassc.gemspec
Also:
1. Compile via `mkmf` instead of libsass's own Makefile. This is necessary to make cross-compilation work (rake-compiler hooks into mkmf).
2. Do not use per-ruby versions of `libsass.so`. It is unnecessary, because `libsass.so` is Ruby-agnostic (the FFI gem is used instead to use it from any Ruby version).
3. Add VERSION file to the non-precompiled gem (as the git information is not available when installing).
4. Clean before every build.
> Link C/C++ stdlib statically for binary gems

- README.md
- test/native_test.rb
Includes hotfix for #128 (https://github.com/sass/libsass/commit/0328de2ad645b1ea017d0482b4d637e9aa5eb40f)
Fixes #128
> Update libsass to 3.6.1

- ext/extconf.rb
- sassc.gemspec
This ensures VERSION is updated when the repo is updated
> extconf.rb: Always write VERSION if we have .git

- lib/sassc/functions_handler.rb
- test/functions_test.rb
fixes https://github.com/rails/sprockets/issues/581 https://github.com/sass/sassc-rails/issues/121
I think there should be a better way to define custom functions, but unfortunatelly that would require changes in the API.
sprockets redefines functions which is super hacky
https://github.com/rails/sprockets/blob/1bcee8ebc03489eb7e42ee5c258a712443a6df3c/lib/sprockets/sassc_processor.rb#L58
https://github.com/rails/sprockets/blob/0cb3314368f9f9e84343ebedcc09c7137e920bc4/lib/sprockets/utils.rb#L126
> thread safe function helpers

- Rakefile
Looks like it is no longer pre-installed by default.
> Install bundler in Docker for `rake gem:native`

- lib/sassc/native.rb
Fixes sass/sassc-ruby#146. See also opal/c_lexer#1 for some discussion on the issue.
> Fix LoadError on some non-rvm environments

- lib/sassc/native.rb
* Since libsass is meant to be used with FFI, `RbConfig::CONFIG['SOEXT']`
would be better, but DLEXT is used as libsass is compiled by mkmf (#127).
* Use `RbConfig::MAKEFILE_CONFIG['DLEXT']` instead of just `RbConfig::CONFIG['DLEXT']`
so it's also correct on JRuby and not 'jar'. See
https://github.com/rake-compiler/rake-compiler/blob/f808dd7a/lib/rake/extensiontask.rb#L41
* This lets Ruby implementations use another file extension than .so/.bundle
for C extensions. For example, TruffleRuby 19.3.0 uses .dylib on macOS.
* Some OS also use a different file extension, such as HPUX which uses .sl.
This allows `sassc` to work again on TruffleRuby on macOS: https://github.com/oracle/truffleruby/issues/1819
cc @bolandrm @glebm
> Use RbConfig::MAKEFILE_CONFIG['DLEXT'] instead of hardcoding extensions

- .travis.yml
* To ensure `sassc` keeps working on TruffleRuby.
For instance `sassc` broke on TruffleRuby when switching to `mkmf` (https://github.com/sass/sassc-ruby/pull/127) but now works again (https://github.com/oracle/truffleruby/issues/1753).
> Test on TruffleRuby in TravisCI

- ext/extconf.rb
Gem won't install on Mac OS X (Mohave) due to a compile error:
`libsass.bundle malformed object (unknown load command 7)`
This is in the code line which strips libsass.bundle of symbols. So this "fix" removes that command. I'm sure there's a better way, but this fixed the problem for me. Not sure why the bundle needs to be stripped or why Mac OS X has an issue with it.h
> Fix compile issue on Mac OS X

- ext/extconf.rb
Despite the warnings, people still build using a different environment than the deployment one.
This change doesn't actually make the built library portable, just less likely to crash on a different CPU.
Refs #146
> Default --march-tune-native to false

- ext/extconf.rb
I think this is a better solution than https://github.com/sass/sassc-ruby/pull/174
> Restore strip symbols

- lib/sassc/engine.rb
- lib/sassc/functions_handler.rb
- lib/sassc/script.rb
- test/functions_test.rb
my intention is to fix thread safety problems https://github.com/sass/sassc-ruby/issues/133 and https://github.com/rails/sprockets/issues/581
and eventually remove
https://github.com/rails/sprockets/blob/0cb3314368f9f9e84343ebedcc09c7137e920bc4/lib/sprockets/utils.rb#L126
sassc doesn't allow you to use different functions for different contexts easily
you can customize functions by patching `Sassc::Script::Functions`, but there's a race condition if you do this at runtime
this patch will allow you to pass custom functions like this
```
module MyModule
def asset_path(path, _options = {})
end
end
SassC::Engine.new(sass, style: :compressed).render # default Sassc::Script::Functions
SassC::Engine.new(sass, style: :compressed, functions: MyModule).render # custom
```
what do you think?
> allow passing functions directly

- lib/sassc/engine.rb
Set appropriate encoding for the string `@source_map` of `Engine`, similarly to that of the string `css` in `Engine#render`.
This PR will fix the error in the last line of the following code:
```ruby
require "sassc"
template = <<EOS
body {
// 赤
color: red;
}
EOS
options = {
:source_map_file => "foo.css.map",
:source_map_contents => true
}
engine = SassC::Engine.new(template, options)
engine.render
source_map = engine.source_map
puts source_map             # includes non-ASCII character "赤"
puts source_map.encoding    # => ASCII-8BIT (UTF-8 is expected)
source_map.encode("UTF-8")  # throws Encoding::UndefinedConversionError
```
> Set appropriate encoding for source_map

- ext/extconf.rb
Sort input file list
so that `libsass.so` builds in a reproducible way
in spite of indeterministic filesystem readdir order.
See https://reproducible-builds.org/ for why this is good.
This PR was done while working on reproducible builds for openSUSE.
Package is called `rubygem-sassc` there.
The only other problem is that `--disable-march-tune-native` is not the default, so results vary depending on build worker CPU. Could also be selected if the `SOURCE_DATE_EPOCH` env var is set.
> Sort input file list

- ext/extconf.rb
darwin nix's clang doesn't support -lto
this PR disables -lto flag for darwin + nix
see https://github.com/sass/sassc-ruby/issues/148 for more context
> disable lto flag for darwin + nix

- Rakefile
As discussed in https://github.com/sass/sassc-ruby/issues/195, `rake gem:native` is currently broken, preventing a new release.
The error is:
```
Package g++-multilib is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'g++-multilib' has no installation candidate
rake aborted!
```
I looked around and apparently this package is outdated an no longer available. However it's used for cross compiling for 32bit packages.
If we looked at downloaded packages:
- https://rubygems.org/gems/sassc/versions/2.1.0-x86_64-linux 500K downloads
- https://rubygems.org/gems/sassc/versions/2.1.0-x86-linux (32bits) 756 downloads.
I think it's safe to say that close to nobody downloads the 32 …
> Fix rake gem:native task

- .travis.yml
This Pull Request adds `2.7.0` entry to `.travis.yml` since Ruby 2.7.0 was released a few months ago and it worth testing against.
> Test against Ruby 2.7.0

- ext/extconf.rb
This got sassc-ruby working for me using Nix on Darwin.
> Fix check to disable LTO by default

- README.md
https://github.com/sass/dart-sass/pull/2282#issuecomment-2417427987
> Mark end-of-life
